1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [11]:
import numpy as np

# Take user input to create a NumPy array
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

# Initialize an empty array
arr = np.empty((rows, cols), dtype=int)

# Fill the array with user input values
for i in range(rows):
    for j in range(cols):
        arr[i, j] = int(input(f"Enter the value for arr[{i}, {j}]: "))

# Display the created array
print("\nCreated NumPy Array:")
print(arr)
#Array Indexing
element1 = arr[1, 1]
#Fancy Indexing
fancy_row= np.array([0,2])
fancy_col= np.array([0,1])
element2= arr[fancy_row,fancy_col]
print("Array Indexing:",element1)
print("Fancy Indexing:",element2 )


Created NumPy Array:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
Array Indexing: 11
Fancy Indexing: [16  7]


Q2. Execute the 2D array Slicing.

In [12]:
import numpy as np

# Take user input for the dimensions of the matrix
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

# Initialize an empty matrix
matrix = np.empty((rows, cols), dtype=int)

# Fill the matrix with user input values
for i in range(rows):
    for j in range(cols):
        matrix[i, j] = int(input(f"Enter the value for matrix[{i}, {j}]: "))

# Display the user-created matrix
print("\nUser-created matrix:")
print(matrix)

# Slicing operations
print("\nSlicing Operations:")

# Slice a submatrix from the user input matrix
start_row = int(input("Enter the start row index: "))
end_row = int(input("Enter the end row index: ")) + 1  # Add 1 to include the end row
start_col = int(input("Enter the start column index: "))
end_col = int(input("Enter the end column index: ")) + 1  # Add 1 to include the end column

submatrix = matrix[start_row:end_row, start_col:end_col]

print("\nSliced submatrix:")
print(submatrix)



User-created matrix:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Slicing Operations:

Sliced submatrix:
[[6 5 4]
 [3 2 1]]


Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [18]:
import numpy as np

# Create a 5-dimensional array with the values 1, 2, 3, 4, and 5
array = np.array([1, 2, 3, 4, 5], ndmin=5)

# Print the array
print(array)

# Print the number of dimensions of the array
print(array.ndim)


[[[[[1 2 3 4 5]]]]]
5


Q4. Reshape the array from 1-D to 2-D array.

In [20]:
import numpy as np

# Take user input to create a 1-D array
input_string = input("Enter elements separated by spaces: ")
input_list = input_string.split()
array_1d = np.array(input_list, dtype=int)

# Determine the shape of the 2-D array
rows = int(input("Enter the number of rows for the 2-D array: "))
cols = int(input("Enter the number of columns for the 2-D array: "))

# Check if the number of elements in the 1-D array matches the desired shape
if rows * cols != array_1d.size:
    print("Error: The product of rows and columns must equal the number of elements in the 1-D array.")
else:
    # Reshape the 1-D array into a 2-D array
    array_2d = array_1d.reshape(rows, cols)

    # Print the original 1-D array and the reshaped 2-D array
    print("\nOriginal 1-D array:")
    print(array_1d)

    print("\nReshaped 2-D array:")
    print(array_2d)



Original 1-D array:
[1 4 7 8 5 2 0 3 6]

Reshaped 2-D array:
[[1 4 7]
 [8 5 2]
 [0 3 6]]


Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [23]:
import numpy as np

# Function to take user input for an array
def input_array():
    input_string = input("Enter elements separated by spaces: ")
    input_list = input_string.split()
    return np.array(input_list, dtype=int)

# Take user input to create three arrays
print("Enter elements for the first array:")
array1 = input_array()

print("Enter elements for the second array:")
array2 = input_array()

print("Enter elements for the third array:")
array3 = input_array()

# stack(): Stacks arrays along a new axis
stacked_arrays = np.stack((array1, array2, array3))
print("\nstacked_arrays:")
print(stacked_arrays)

# hstack(): Stacks arrays horizontally (along columns)
hstacked_arrays = np.hstack((array1, array2, array3))
print("\nhstacked_arrays:")
print(hstacked_arrays)

# vstack(): Stacks arrays vertically (along rows)
vstacked_arrays = np.vstack((array1, array2, array3))
print("\nvstacked_arrays:")
print(vstacked_arrays)

# dstack(): Stacks arrays along the third dimension (depth)
# Create 2-D arrays for dstack()
array4 = np.array([[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]])

array5 = np.array([[19, 20, 21],
                   [22, 23, 24],
                   [25, 26, 27]])

dstacked_arrays = np.dstack((array4, array5))
print("\ndstacked_arrays:")
print(dstacked_arrays)


Enter elements for the first array:
Enter elements for the second array:
Enter elements for the third array:

stacked_arrays:
[[1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1]
 [1 5 9 8 4 7 6 2 3]]

hstacked_arrays:
[1 2 3 4 5 6 7 8 9 9 8 7 6 5 4 3 2 1 1 5 9 8 4 7 6 2 3]

vstacked_arrays:
[[1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1]
 [1 5 9 8 4 7 6 2 3]]

dstacked_arrays:
[[[10 19]
  [11 20]
  [12 21]]

 [[13 22]
  [14 23]
  [15 24]]

 [[16 25]
  [17 26]
  [18 27]]]


Q6. Perform the searchsort method in Numpy array.

In [29]:
import numpy as np

# Function to take user input for a sorted array
def input_sorted_array():
    input_string = input("Enter sorted elements separated by spaces: ")
    input_list = input_string.split()
    return np.array(input_list, dtype=int)

# Take user input to create a sorted array
print("Enter sorted elements for the array:")
sorted_array = input_sorted_array()

# Sort the array (in ascending order)
sorted_array.sort()

# Print the sorted array
print("\nSorted Array:")
print(sorted_array)

# Value to search for
value_to_find = int(input("Enter the value to find in the sorted array: "))

# Use searchsorted to find the index where the value should be inserted
index_to_insert = np.searchsorted(sorted_array, value_to_find)

# Print the result
print(f"The value {value_to_find} should be inserted at index {index_to_insert} to maintain the sorted order.")


Enter sorted elements for the array:

Sorted Array:
[1 4 5 5 7 8 9]
The value 16 should be inserted at index 7 to maintain the sorted order.


Q7. Create Numpy Structured array using your domain features.

In [35]:
import numpy as np

# Define the data type for the structured array
product_dtype = np.dtype([
    ('ProductID', 'int32'),         # Product ID as an integer
    ('ProductName', 'U50'),         # Product name as a Unicode string (up to 50 characters)
    ('Price', 'float64'),           # Price as a floating-point number
    ('Quantity', 'int32')           # Quantity as an integer
])

# Create a structured array with product information
products = np.array([
    (101, 'Scribble Pad A', 5.99, 100),
    (102, 'Scribble Pad B', 4.49, 50),
    (103, 'Scribble Pad C', 6.99, 75),
    (104, 'Scribble Pad D', 7.49, 60),
    (105, 'Scribble Pad E', 3.99, 200)
], dtype=product_dtype)

# Print the structured array
print("Structured Array - Product Information:")
print(products)


Structured Array - Product Information:
[(101, 'Scribble Pad A', 5.99, 100) (102, 'Scribble Pad B', 4.49,  50)
 (103, 'Scribble Pad C', 6.99,  75) (104, 'Scribble Pad D', 7.49,  60)
 (105, 'Scribble Pad E', 3.99, 200)]


Q8. Create Data frame using List and Dictionary.

In [30]:
import pandas as pd

# Create a list of dictionaries
data = [{'NAME': 'Tushar', 'AGE': 22}, {'NAME': 'Rohit', 'AGE': 21}]

# Create a DataFrame from the list of dictionaries
df = pd.DataFrame.from_dict(data)

# Print the DataFrame
print(df)


     NAME  AGE
0  Tushar   22
1   Rohit   21


Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [33]:
import pandas as pd
import numpy as np

# Create a sample DataFrame with missing data in a scribble pad inventory
data = {
    'ProductID': [101, 102, 103, 104, 105],
    'ProductName': ['Scribble Pad A', 'Scribble Pad B', 'Scribble Pad C', np.nan, 'Scribble Pad E'],
    'Price': [5.99, 4.49, np.nan, 6.99, 3.99],
    'Quantity': [100, 50, 75, np.nan, 200]
}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame - Scribble Pad Inventory:")
print(df)

# 1. isnull() - Detect missing values
missing_data = df.isnull()
print("\nMissing Data (isnull()):")
print(missing_data)

# 2. notnull() - Detect non-missing values
non_missing_data = df.notnull()
print("\nNon-Missing Data (notnull()):")
print(non_missing_data)

# 3. dropna() - Remove rows with missing data
df_dropped = df.dropna()
print("\nDataFrame after dropping rows with missing data (dropna()):")
print(df_dropped)

# 4. fillna() - Fill missing values with a specific value or strategy
df_filled = df.fillna({'Price': df['Price'].mean(), 'Quantity': 0})
print("\nDataFrame after filling missing values (fillna()):")
print(df_filled)

# 5. replace() - Replace specific values with another value
df_replaced = df.replace(np.nan, 'Unknown', regex=True)
print("\nDataFrame after replacing missing values (replace()):")
print(df_replaced)

# 6. interpolate() - Interpolate missing values using various methods
df_interpolated = df.interpolate()
print("\nDataFrame after interpolating missing values (interpolate()):")
print(df_interpolated)


Original DataFrame - Scribble Pad Inventory:
   ProductID     ProductName  Price  Quantity
0        101  Scribble Pad A   5.99     100.0
1        102  Scribble Pad B   4.49      50.0
2        103  Scribble Pad C    NaN      75.0
3        104             NaN   6.99       NaN
4        105  Scribble Pad E   3.99     200.0

Missing Data (isnull()):
   ProductID  ProductName  Price  Quantity
0      False        False  False     False
1      False        False  False     False
2      False        False   True     False
3      False         True  False      True
4      False        False  False     False

Non-Missing Data (notnull()):
   ProductID  ProductName  Price  Quantity
0       True         True   True      True
1       True         True   True      True
2       True         True  False      True
3       True        False   True     False
4       True         True   True      True

DataFrame after dropping rows with missing data (dropna()):
   ProductID     ProductName  Price  Quantity

C:\Users\tushar sakuja\AppData\Local\Temp\ipykernel_2524\3986800269.py:44: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolated = df.interpolate()


Q10. Perform the Hierarchical Indexing in the above created dataset.

In [34]:
import pandas as pd

# Create a sample DataFrame
data = {
    'ProductID': [101, 102, 103, 104, 105],
    'ProductName': ['Scribble Pad A', 'Scribble Pad B', 'Scribble Pad C', 'Scribble Pad D', 'Scribble Pad E'],
    'Price': [5.99, 4.49, 6.99, 7.49, 3.99],
    'Quantity': [100, 50, 75, 60, 200]
}

df = pd.DataFrame(data)

# Create hierarchical indexing
df.set_index(['ProductID', 'ProductName'], inplace=True)

# Display the DataFrame with hierarchical indexing
print("DataFrame with Hierarchical Indexing:")
print(df)


DataFrame with Hierarchical Indexing:
                          Price  Quantity
ProductID ProductName                    
101       Scribble Pad A   5.99       100
102       Scribble Pad B   4.49        50
103       Scribble Pad C   6.99        75
104       Scribble Pad D   7.49        60
105       Scribble Pad E   3.99       200
